// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsJt7GumYerQlUiqZqGG-uQTa-NL5xl3k',
    appId: '1:60478017512:web:3ed9674abbf6ed69731e5d',
    messagingSenderId: '60478017512',
    projectId: 'tandau-app',
    authDomain: 'tandau-app.firebaseapp.com',
    storageBucket: 'tandau-app.firebasestorage.app',
    measurementId: 'G-D0663BVNKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5RML9VM-h0-vLMs5CBcuqoNiaP8j44aU',
    appId: '1:60478017512:android:89360d3b214edfff731e5d',
    messagingSenderId: '60478017512',
    projectId: 'tandau-app',
    storageBucket: 'tandau-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0CRCfmru95DTk5xv8AaAQbd9etHJ7Rjo',
    appId: '1:60478017512:ios:d86487c87bd26cc1731e5d',
    messagingSenderId: '60478017512',
    projectId: 'tandau-app',
    storageBucket: 'tandau-app.firebasestorage.app',
    iosBundleId: 'com.example.tandau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0CRCfmru95DTk5xv8AaAQbd9etHJ7Rjo',
    appId: '1:60478017512:ios:d86487c87bd26cc1731e5d',
    messagingSenderId: '60478017512',
    projectId: 'tandau-app',
    storageBucket: 'tandau-app.firebasestorage.app',
    iosBundleId: 'com.example.tandau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsJt7GumYerQlUiqZqGG-uQTa-NL5xl3k',
    appId: '1:60478017512:web:95170cd655475c9c731e5d',
    messagingSenderId: '60478017512',
    projectId: 'tandau-app',
    authDomain: 'tandau-app.firebaseapp.com',
    storageBucket: 'tandau-app.firebasestorage.app',
    measurementId: 'G-9LMWG5V6PX',
  );
}
