import json
import os

UNIVERSITIES = [
    # ASTANA
    {"id": "1", "name": "Назарбаев Университеті", "city": "Астана", "logoUrl": "assets/images/nu_logo.png", "imageUrls": ["assets/images/nu_campus.jpg"], "majors": ["Инженерия", "Компьютерлік ғылымдар", "Бизнес", "Медицина", "Гуманитарлық ғылымдар", "Әлеуметтік ғылымдар", "Табиғат ғылымдары"], "passingScore": 85, "tuitionRange": "Грант немесе ~7,775,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Назарбаев Университеті — Қазақстандағы алғашқы зерттеу университеті. Халықаралық стандарттарға сәйкес білім береді.", "contactPhone": "+7 (7172) 70-66-88", "email": "nu@nu.edu.kz", "requirements": ["ЕНТ ағылшын тілі 85+", "GPA 4.0/5.0", "IELTS 6.0+", "NUET вступительный тест", "Мотивациялық хат"], "applicationDeadline": "15 мамыр, 2026", "address": "Қабанбай батыр даңғылы 53, Астана", "website": "nu.edu.kz", "averageRating": 4.8, "studentCount": 6045},
    {"id": "2", "name": "Astana IT University", "city": "Астана", "logoUrl": "assets/images/aitu_logo.png", "imageUrls": ["assets/images/aitu_campus.jpg"], "majors": ["Компьютерлік ғылымдар", "Бағдарламалық инженерия", "Киберқауіпсіздік", "Big Data Analytics", "Жасанды интеллект", "Smart технологиялар", "IT менеджмент"], "passingScore": 75, "tuitionRange": "2,500,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Astana IT University — IT саласына мамандандырылған заманауи университет. EXPO аумағында орналасқан.", "contactPhone": "+7 (7172) 645-716", "email": "info@astanait.edu.kz", "requirements": ["AITU Excellence Test (25-50 балл)", "ЕНТ сертификаты", "IELTS немесе STEP KBTU", "Портфолио"], "applicationDeadline": "10 шілде, 2026", "address": "Мәңгілік Ел даңғылы 55/11, Блок С1, EXPO, Астана", "website": "astanait.edu.kz", "averageRating": 4.7, "studentCount": 3500},
    {"id": "3", "name": "Л.Н. Гумилев атындағы ЕҰУ", "city": "Астана", "logoUrl": "assets/images/enu_logo.png", "imageUrls": ["assets/images/enu_campus.jpg"], "majors": ["Заң", "Экономика", "Халықаралық қатынастар", "Филология", "IT", "Педагогика", "Инженерия", "Тарих", "Журналистика"], "passingScore": 65, "tuitionRange": "Грант немесе ~1,350,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Л.Н. Гумилев атындағы Еуразия ұлттық университеті — Астанадағы ірі классикалық университет. 160+ білім беру бағдарламасы.", "contactPhone": "+7 (7172) 709-500", "email": "enu@enu.kz", "requirements": ["ЕНТ 65+ (ұлттық ЖОО үшін)", "Құжаттар топтамасы", "Медициналық анықтама"], "applicationDeadline": "18 шілде, 2026", "address": "Сәтпаев көшесі 2, Астана", "website": "enu.kz", "averageRating": 4.5, "studentCount": 20350},
    {"id": "4", "name": "Астана Медицина Университеті (АМУ)", "city": "Астана", "logoUrl": "assets/images/amu_logo.png", "imageUrls": ["assets/images/amu_campus.jpg"], "majors": ["Жалпы медицина", "Стоматология", "Фармация", "Қоғамдық денсаулық сақтау", "Мейірбике ісі"], "passingScore": 75, "tuitionRange": "Грант немесе 1,200,000 - 1,800,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Елордадағы жетекші медициналық жоғары оқу орны. Теориялық және практикалық дайындық, заманауи клиникалық база.", "contactPhone": "+7 (7172) 539-445", "email": "info@amu.kz", "requirements": ["ЕНТ 75+ (Биология, Химия)", "Медициналық анықтама", "Психометриялық тест"], "applicationDeadline": "20 тамыз, 2026", "address": "Бейбітшілік көшесі 49/А, Астана", "website": "amu.kz", "averageRating": 4.4, "studentCount": 8500},
    {"id": "5", "name": "С. Сейфуллин атындағы ҚазАТУ", "city": "Астана", "logoUrl": "assets/images/kazatu_logo.png", "imageUrls": ["assets/images/kazatu_campus.jpg"], "majors": ["Агрономия", "Ветеринария", "Инженерия", "Экономика", "IT в агросекторе", "Жерге орналастыру", "Энергетика"], "passingScore": 60, "tuitionRange": "Грант немесе ~800,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Агротехникалық саладағы басты университеттердің бірі. Ауыл шаруашылығы және инженерлік бағыттар.", "contactPhone": "+7 (7172) 317-547", "email": "info@kazatu.kz", "requirements": ["ЕНТ 60+", "Жалпы құжаттар"], "applicationDeadline": "25 тамыз, 2026", "address": "Жеңіс даңғылы 62, Астана", "website": "kazatu.edu.kz", "averageRating": 4.2, "studentCount": 11000},
    {"id": "6", "name": "Maqsut Narikbayev University (KAZGUU)", "city": "Астана", "logoUrl": "assets/images/kazguu_logo.png", "imageUrls": ["assets/images/kazguu_campus.jpg"], "majors": ["Құқықтану", "Экономика", "Халықаралық қатынастар", "Аударма ісі", "Менеджмент", "IT"], "passingScore": 70, "tuitionRange": "1,600,000 - 2,500,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Құқық және экономика саласындағы үздік оқу орындарының бірі. Жоғары сапалы оқыту, халықаралық тану.", "contactPhone": "+7 (7172) 703-030", "email": "info@kazguu.kz", "requirements": ["ЕНТ 70+", "Ағылшын тілі деңгейі (мамандыққа байланысты)"], "applicationDeadline": "20 тамыз, 2026", "address": "Қорғалжын тас жолы 8, Астана", "website": "kazguu.kz", "averageRating": 4.6, "studentCount": 6000},

    # ALMATY
    {"id": "7", "name": "Әл-Фараби атындағы ҚазҰУ", "city": "Алматы", "logoUrl": "assets/images/kaznu_logo.png", "imageUrls": ["assets/images/kaznu_campus.jpg"], "majors": ["IT", "Экономика", "Педагогика", "Медицина", "Заң", "Биология", "Филология", "Тарих", "Физика", "Математика", "Журналистика"], "passingScore": 65, "tuitionRange": "Грант немесе 1,100,000 - 1,900,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Әл-Фараби атындағы Қазақ ұлттық университеті — Қазақстандағы ең ірі және ең көне университет (1934 ж.). 16 факультет, 550+ білім беру бағдарламасы.", "contactPhone": "+7 (727) 377-33-33", "email": "info@kaznu.edu.kz", "requirements": ["ЕНТ 65+ (ұлттық ЖОО)", "Құжаттар топтамасы", "Медициналық анықтама"], "applicationDeadline": "20 шілде, 2026", "address": "Әл-Фараби даңғылы 71, Алматы", "website": "kaznu.kz", "averageRating": 4.6, "studentCount": 25000},
    {"id": "8", "name": "Сәтбаев Университеті (ҚазҰТУ)", "city": "Алматы", "logoUrl": "assets/images/satbayev_logo.png", "imageUrls": ["assets/images/satbayev_campus.jpg"], "majors": ["Инженерия", "Тау-кен ісі", "IT", "Дизайн", "Компьютерлік ғылымдар", "Робототехника", "Металлургия", "Сәулет"], "passingScore": 65, "tuitionRange": "Грант немесе 750,000 - 1,600,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Сәтбаев Университеті — техникалық және инженерлік мамандықтарға мамандандырылған ірі университет. QS World University Rankings рейтингінде беделді орынға ие.", "contactPhone": "+7 (727) 292-60-25", "email": "info@satbayev.university", "requirements": ["ЕНТ 65+ (ұлттық ЖОО)", "Физика және математика бойынша жоғары балл"], "applicationDeadline": "15 шілде, 2026", "address": "Сәтпаев көшесі 22а, Алматы", "website": "satbayev.university", "averageRating": 4.5, "studentCount": 9000},
    {"id": "9", "name": "Абай атындағы ҚазҰПУ", "city": "Алматы", "logoUrl": "assets/images/kaznpu_logo.png", "imageUrls": ["assets/images/kaznpu_campus.jpg"], "majors": ["Педагогика", "Психология", "Филология", "Тарих", "Өнер", "Математика", "Биология", "Халықаралық қатынастар", "Заң", "Информатика"], "passingScore": 65, "tuitionRange": "Грант немесе ~950,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Қазақ ұлттық педагогикалық университеті — Қазақстандағы ең ірі педагогикалық ЖОО. 12 843 студент. QS Asia 2026 рейтингінде 131-орын.", "contactPhone": "+7 (727) 291-57-68", "email": "rector@abaiuniversity.edu.kz", "requirements": ["ЕНТ 65+ (ұлттық ЖОО)", "Педагогика 75+"], "applicationDeadline": "20 шілде, 2026", "address": "Достық даңғылы 13, Алматы", "website": "kaznpu.kz", "averageRating": 4.4, "studentCount": 12843},
    {"id": "10", "name": "Қазақ-Британ Техникалық Университеті (KBTU)", "city": "Алматы", "logoUrl": "assets/images/kbtu_logo.png", "imageUrls": ["assets/images/kbtu_campus.jpg"], "majors": ["IT", "Мұнай-газ ісі", "Бизнес", "Инженерия", "Қаржы", "Маркетинг", "Химиялық инженерия", "Урандық іс"], "passingScore": 70, "tuitionRange": "Грант немесе 2,100,000 - 2,400,000 ₸/жыл", "hasDormitory": False, "hasGrants": True, "description": "KBTU — Британдық білім беру стандарттарымен жұмыс істейтін техникалық университет. 80% студент гранттармен оқиды.", "contactPhone": "+7 (727) 357-42-51", "email": "info@kbtu.kz", "requirements": ["ЕНТ 70+", "IELTS 5.5+ немесе STEP KBTU B1"], "applicationDeadline": "1 шілде, 2026", "address": "Төле би көшесі 59, Алматы", "website": "kbtu.kz", "averageRating": 4.6, "studentCount": 6182},
    {"id": "11", "name": "Нархоз Университеті", "city": "Алматы", "logoUrl": "assets/images/keu_logo.png", "imageUrls": ["assets/images/keu_campus.jpg"], "majors": ["Экономика", "Қаржы", "Маркетинг", "Менеджмент", "Заң", "IT in Business", "Халықаралық қатынастар", "Психология", "Саясаттану"], "passingScore": 50, "tuitionRange": "Грант немесе ~1,500,000 - 2,000,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Нархоз Университеті — экономика, бизнес және қоғамдық ғылымдарға мамандандырылған университет. Жаңа кампус.", "contactPhone": "+7 (727) 377-12-55", "email": "narxoz@narxoz.kz", "requirements": ["ЕНТ 50+ (негізгі мамандықтар 75+)"], "applicationDeadline": "15 шілде, 2026", "address": "Жандосов көшесі 55, Алматы", "website": "narxoz.kz", "averageRating": 4.3, "studentCount": 7281},
    {"id": "12", "name": "Сүлейман Демирел Атындағы Университет (SDU)", "city": "Алматы (Қаскелең)", "logoUrl": "assets/images/sdu_logo.png", "imageUrls": ["assets/images/sdu_campus.jpg"], "majors": ["IT", "Математика", "Құқық", "Журналистика", "Экономика", "Бизнес мектеп", "Филология"], "passingScore": 65, "tuitionRange": "1,500,000 - 2,200,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "SDU — халықаралық университет, оқыту негізінен ағылшын тілінде. Мұнда күшті IT және гуманитарлық мектептер бар.", "contactPhone": "+7 (727) 307-95-65", "email": "info@sdu.edu.kz", "requirements": ["ЕНТ 65+", "IELTS 5.5+", "SDU SPT Test"], "applicationDeadline": "15 тамыз, 2026", "address": "Абылай хан көшесі 1/1, Қаскелең", "website": "sdu.edu.kz", "averageRating": 4.7, "studentCount": 8500},
    {"id": "13", "name": "International IT University (IITU)", "city": "Алматы", "logoUrl": "assets/images/iitu_logo.png", "imageUrls": ["assets/images/iitu_campus.jpg"], "majors": ["Компьютерлік ғылымдар", "Бағдарламалық инженерия", "Ақпараттық қауіпсіздік", "Телекоммуникация", "Журналистика (IT)", "Экономика (IT)"], "passingScore": 75, "tuitionRange": "Грант немесе 1,800,000 - 2,100,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "IITU - Қазақстандағы жетекші АТ-университеті. Ағылшын тілінде оқыту.", "contactPhone": "+7 (727) 330-85-62", "email": "info@iitu.edu.kz", "requirements": ["ЕНТ 75+", "Ағылшын тілінен тест"], "applicationDeadline": "20 тамыз, 2026", "address": "Манас көшесі 34/1, Алматы", "website": "iitu.edu.kz", "averageRating": 4.5, "studentCount": 6500},
    {"id": "14", "name": "Қазақ Ұлттық Аграрлық Зерттеу Университеті (ҚазҰАЗУ)", "city": "Алматы", "logoUrl": "assets/images/kaznau_logo.png", "imageUrls": ["assets/images/kaznau_campus.jpg"], "majors": ["Агрономия", "Ветеринария", "Биотехнология", "Су ресурстары", "Орман шаруашылығы", "ИТ агро-сектор"], "passingScore": 55, "tuitionRange": "Грант немесе 600,000 - 900,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Ауыл шаруашылығы бойынша көшбасшы университет, заманауи зерттеу орталықтары бар.", "contactPhone": "+7 (727) 264-16-11", "email": "info@kaznau.kz", "requirements": ["ЕНТ 55+"], "applicationDeadline": "25 тамыз, 2026", "address": "Абай даңғылы 8, Алматы", "website": "kaznau.kz", "averageRating": 4.1, "studentCount": 9000},
    {"id": "15", "name": "Қазақ Ұлттық Медицина Университеті (ҚазҰМУ)", "city": "Алматы", "logoUrl": "assets/images/kaznmu_logo.png", "imageUrls": ["assets/images/kaznmu_campus.jpg"], "majors": ["Жалпы медицина", "Стоматология", "Педиатрия", "Фармация", "Қоғамдық денсаулық"], "passingScore": 85, "tuitionRange": "Грант немесе 1,300,000 - 2,000,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "С. Асфендияров атындағы ең көне әрі беделді медициналық университет.", "contactPhone": "+7 (727) 338-70-90", "email": "info@kaznmu.kz", "requirements": ["ЕНТ 85+ (Биология/Химия)", "Психометриялық тест", "Медициналық анықтама"], "applicationDeadline": "20 тамыз, 2026", "address": "Төле би көшесі 94, Алматы", "website": "kaznmu.edu.kz", "averageRating": 4.6, "studentCount": 11000},

    # SHYMKENT
    {"id": "16", "name": "М.О. Әуезов атындағы Оңтүстік Қазақстан университеті", "city": "Шымкент", "logoUrl": "assets/images/auezov_logo.png", "imageUrls": ["assets/images/auezov_campus.jpg"], "majors": ["Филология", "Экономика", "Құқық", "IT", "Инженерия", "Әлеуметтік ғылымдар", "Менеджмент"], "passingScore": 72, "tuitionRange": "Грант немесе ~700,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "1943 жылы құрылған ұлттық мәртебесі бар ірі университет — ОҚ-дағы ең ірі ЖОО. ~17 303 студент.", "contactPhone": "8 (725) 221-08-94", "email": "pk_ukgu@mail.ru", "requirements": ["Паспорт", "Аттестат/Диплом", "ҰБТ (72+)"], "applicationDeadline": "20 тамыз, 2026", "address": "Тәуке хан даңғылы, 5, Шымкент", "website": "auezov.edu.kz", "averageRating": 4.4, "studentCount": 17303},
    {"id": "17", "name": "Оңтүстік Қазақстан медицина академиясы (ОҚМА)", "city": "Шымкент", "logoUrl": "assets/images/skma_logo.png", "imageUrls": ["assets/images/skma_campus.jpg"], "majors": ["Жалпы медицина", "Педиатрия", "Стоматология", "Мейірбике ісі", "Қоғамдық денсаулық сақтау", "Фармация"], "passingScore": 75, "tuitionRange": "900,000 - 1,800,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Оңтүстік Қазақстан медицина академиясы — 1979 жылы құрылған жеке меншік медициналық жоғары оқу орны.", "contactPhone": "8 (725) 239-57-57", "email": "medacadem@rambler.ru", "requirements": ["Аттестат/Диплом", "ҰБТ (Биология, Химия)", "Медициналық анықтама (086-У)"], "applicationDeadline": "22 тамыз, 2026", "address": "Әл-Фараби алаңы, 1/1, Шымкент", "website": "skma.edu.kz", "averageRating": 4.3, "studentCount": 5000},
    {"id": "18", "name": "Ө. Жәнібеков атындағы ОҚМПУ", "city": "Шымкент", "logoUrl": "assets/images/okmpu_logo.png", "imageUrls": ["assets/images/okmpu_campus.jpg"], "majors": ["Педагогика", "Жаратылыстану ғылымдары", "Тарих", "Филология", "Әлеуметтік ғылымдар", "Психология"], "passingScore": 82, "tuitionRange": "600,000 - 750,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Өзбекәлі Жәнібеков атындағы Оңтүстік Қазақстан педагогикалық университеті. ОҚ-да мұғалімдер даярлау саласының көшбасшысы.", "contactPhone": "8 (725) 221-40-06", "email": "info@okmpu.kz", "requirements": ["Аттестат", "ҰБТ 82+ (педагогика)"], "applicationDeadline": "20 тамыз, 2026", "address": "А. Байтұрсынов көшесі, 13, Шымкент", "website": "okmpu.kz", "averageRating": 4.2, "studentCount": 5773},
    {"id": "19", "name": "Мирас университеті", "city": "Шымкент", "logoUrl": "assets/images/miras_logo.png", "imageUrls": ["assets/images/miras_campus.jpg"], "majors": ["Экономика", "Құқық", "IT", "Педагогика", "Дизайн", "Туризм"], "passingScore": 65, "tuitionRange": "510,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "1997 жылы құрылған жеке меншік университет. Қабылдау комиссиясының мақұлдау көрсеткіші жоғары.", "contactPhone": "8 (725) 233-77-77", "email": "info@miras.edu.kz", "requirements": ["Аттестат", "ҰБТ (50+)"], "applicationDeadline": "25 тамыз, 2026", "address": "Ғ. Иляев көшесі, 3, Шымкент", "website": "miras.edu.kz", "averageRating": 4.1, "studentCount": 5471},
    {"id": "20", "name": "Орталық Азия инновациялық университеті (CAIU)", "city": "Шымкент", "logoUrl": "assets/images/caiu_logo.png", "imageUrls": ["assets/images/caiu_campus.jpg"], "majors": ["Педагогика", "Экономика", "Құқықтану", "IT", "Мұнай-газ ісі"], "passingScore": 70, "tuitionRange": "400,000 - 550,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Жаңа форматтағы заманауи университет (CAIU). 30+ мамандық. Әскери кафедра бар.", "contactPhone": "8 (725) 237-12-37", "email": "ukgi2002@mail.ru", "requirements": ["Аттестат", "ҰБТ (50+)"], "applicationDeadline": "25 тамыз, 2026", "address": "Мәделі қожа көшесі, 137, Шымкент", "website": "caiu.edu.kz", "averageRating": 4.0, "studentCount": 12500},

    # KARAGANDA
    {"id": "21", "name": "Е.А. Бөкетов атындағы Қарағанды университеті", "city": "Қарағанды", "logoUrl": "assets/images/karaganda_uni_logo.png", "imageUrls": ["assets/images/karaganda_uni_campus.jpg"], "majors": ["Құқықтану", "Экономика", "Педагогика", "Ақпараттық технологиялар", "Биология", "Физика", "Тарих", "Химия"], "passingScore": 65, "tuitionRange": "650,000 - 1,100,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Қарағанды облысындағы ең ірі университет, 1972 жылы құрылған. ~18 000 студент. Серпін бағдарламасына қатысады.", "contactPhone": "+7 (7212) 77-04-24", "email": "office@ksu.kz", "requirements": ["Аттестат", "ҰБТ сертификаты"], "applicationDeadline": "25 тамыз, 2026", "address": "Университет көшесі, 28, Қарағанды", "website": "ksu.kz", "averageRating": 4.3, "studentCount": 18000},
    {"id": "22", "name": "Қарағанды техникалық университеті (ҚарТУ)", "city": "Қарағанды", "logoUrl": "assets/images/kartu_logo.png", "imageUrls": ["assets/images/kartu_campus.jpg"], "majors": ["Тау-кен ісі", "Металлургия", "Машина жасау", "Ақпараттық жүйелер", "Энергетика", "Құрылыс", "Автоматтандыру"], "passingScore": 60, "tuitionRange": "600,000 - 900,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "1953 жылы құрылған, Орталық Қазақстандағы жетекші техникалық ЖОО. Тау-кен саласының маманы.", "contactPhone": "+7 (7212) 56-59-32", "email": "info@kstu.kz", "requirements": ["Аттестат", "ҰБТ (математика профиль)"], "applicationDeadline": "25 тамыз, 2026", "address": "Бұлқышев көшесі, 56, Қарағанды", "website": "kstu.kz", "averageRating": 4.1, "studentCount": 10000},
    {"id": "23", "name": "Қарағанды медицина университеті", "city": "Қарағанды", "logoUrl": "assets/images/karaganda_med_logo.png", "imageUrls": ["assets/images/karaganda_med_campus.jpg"], "majors": ["Жалпы медицина", "Стоматология", "Фармация", "Қоғамдық денсаулық сақтау", "Мейірбике ісі"], "passingScore": 70, "tuitionRange": "800,000 - 1,500,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Орталық Қазақстандағы жетекші мед.ЖОО. Клиникалық базалар мен симуляциялық орталықтар.", "contactPhone": "+7 (7212) 51-38-79", "email": "info@qmu.kz", "requirements": ["ҰБТ 70+ (биология + химия)", "Медициналық анықтама (075-У)"], "applicationDeadline": "20 тамыз, 2026", "address": "Гоголь көшесі, 40, Қарағанды", "website": "qmu.kz", "averageRating": 4.4, "studentCount": 8000},

    # PAVLODAR
    {"id": "24", "name": "С. Торайғыров атындағы Павлодар университеті", "city": "Павлодар", "logoUrl": "assets/images/pavlodar_uni_logo.png", "imageUrls": ["assets/images/pavlodar_uni_campus.jpg"], "majors": ["Педагогика", "Құқықтану", "Экономика", "Ақпараттық технологиялар", "Металлургия", "Туризм"], "passingScore": 55, "tuitionRange": "500,000 - 900,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Павлодар облысындағы ең ірі ЖОО. Серпін + сельская квота.", "contactPhone": "+7 (7182) 67-36-69", "email": "psu@psu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Ломов көшесі, 64, Павлодар", "website": "psu.kz", "averageRating": 4.0, "studentCount": 12000},
    {"id": "25", "name": "Инновациялық Еуразия университеті", "city": "Павлодар", "logoUrl": "assets/images/ineu_logo.png", "imageUrls": ["assets/images/ineu_campus.jpg"], "majors": ["Бизнес басқару", "Қаржы", "Дизайн", "Ақпараттық жүйелер", "Педагогика", "Психология"], "passingScore": 50, "tuitionRange": "450,000 - 800,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Жеке ЖОО, заманауи кампус, дуалды оқыту жүйесі.", "contactPhone": "+7 (7182) 55-68-11", "email": "ineu@ineu.edu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "М. Горький көшесі, 102/4, Павлодар", "website": "ineu.edu.kz", "averageRating": 3.9, "studentCount": 5000},

    # AKTOBE
    {"id": "26", "name": "Қ. Жұбанов атындағы Ақтөбе өңірлік университеті", "city": "Ақтөбе", "logoUrl": "assets/images/aktobe_uni_logo.png", "imageUrls": ["assets/images/aktobe_uni_campus.jpg"], "majors": ["Педагогика", "Құқықтану", "Экономика", "Ақпараттық технологиялар", "Химия", "Биология", "Тарих"], "passingScore": 55, "tuitionRange": "450,000 - 850,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Батыс Қазақстандағы ең ірі университет. 70+ мамандық.", "contactPhone": "+7 (7132) 56-36-43", "email": "arsu@zhubanov.edu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Братьев Жубановых көшесі, 263, Ақтөбе", "website": "zhubanov.edu.kz", "averageRating": 4.1, "studentCount": 15000},
    {"id": "27", "name": "Марат Оспанов атындағы Батыс Қазақстан медицина университеті", "city": "Ақтөбе", "logoUrl": "assets/images/aktobe_med_logo.png", "imageUrls": ["assets/images/aktobe_med_campus.jpg"], "majors": ["Жалпы медицина", "Стоматология", "Фармация", "Педиатрия"], "passingScore": 75, "tuitionRange": "900,000 - 1,500,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Батыстағы басты медициналық ЖОО.", "contactPhone": "+7 (7132) 56-25-10", "email": "info@zkgmu.kz", "requirements": ["ҰБТ 75+", "Медициналық анықтама"], "applicationDeadline": "20 тамыз, 2026", "address": "Маресьев көшесі 68, Ақтөбе", "website": "zkgmu.kz", "averageRating": 4.3, "studentCount": 6000},

    # ATAIRAU & AKTAU
    {"id": "28", "name": "Х. Досмұхамедов атындағы Атырау университеті", "city": "Атырау", "logoUrl": "assets/images/atyrau_uni_logo.png", "imageUrls": ["assets/images/atyrau_uni_campus.jpg"], "majors": ["Педагогика", "Экономика", "IT", "Журналистика", "Құқық"], "passingScore": 50, "tuitionRange": "500,000 - 800,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Мұнай астанасындағы басты гуманитарлық ЖОО.", "contactPhone": "+7 (7122) 27-63-23", "email": "info@asu.edu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Студенттер даңғылы 1, Атырау", "website": "asu.edu.kz", "averageRating": 4.0, "studentCount": 7500},
    {"id": "29", "name": "Ш. Есенов атындағы Каспий мемлекеттік технологиялар және инжиниринг университеті", "city": "Ақтау", "logoUrl": "assets/images/aktau_uni_logo.png", "imageUrls": ["assets/images/aktau_uni_campus.jpg"], "majors": ["Мұнай-газ ісі", "Теңіз техникасы", "Экономика", "IT", "Экология"], "passingScore": 60, "tuitionRange": "600,000 - 1,000,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Теңіз және мұнай саласына мамандар даярлайтын Каспийдегі басты оқу орны.", "contactPhone": "+7 (7292) 35-15-51", "email": "info@yu.edu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "32 ықшам аудан, Ақтау", "website": "yu.edu.kz", "averageRating": 4.1, "studentCount": 6000},
    
    # KOKSHETAU
    {"id": "30", "name": "Ш. Уәлиханов атындағы Көкшетау университеті", "city": "Көкшетау", "logoUrl": "assets/images/kokshetau_uni_logo.png", "imageUrls": ["assets/images/kokshetau_uni_campus.jpg"], "majors": ["Педагогика", "Ауыл шаруашылығы", "Экономика", "Медицина", "IT"], "passingScore": 55, "tuitionRange": "450,000 - 800,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Көкшетаудағы ең көне университет, жаңадан медицина факультеті ашылған.", "contactPhone": "+7 (7162) 25-55-83", "email": "info@shokan.edu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Абай көшесі 76, Көкшетау", "website": "shokan.edu.kz", "averageRating": 4.1, "studentCount": 8000},

    # TARAZ
    {"id": "31", "name": "М.Х. Дулати атындағы Тараз өңірлік университеті", "city": "Тараз", "logoUrl": "assets/images/taraz_uni_logo.png", "imageUrls": ["assets/images/taraz_uni_campus.jpg"], "majors": ["Су шаруашылығы", "Экономика", "Педагогика", "IT", "Инженерия"], "passingScore": 50, "tuitionRange": "400,000 - 750,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Тараз қаласындағы ең ірі университет.", "contactPhone": "+7 (7262) 45-81-01", "email": "dulaty@tarsu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Төле би көшесі 60, Тараз", "website": "dulaty.kz", "averageRating": 4.0, "studentCount": 14000},

    # SEMEY & Oskemen
    {"id": "32", "name": "Сәрсен Аманжолов атындағы Шығыс Қазақстан университеті", "city": "Өскемен", "logoUrl": "assets/images/vku_logo.png", "imageUrls": ["assets/images/vku_campus.jpg"], "majors": ["Физика", "Математика", "Педагогика", "Жаратылыстану ғылымдары", "Экономика"], "passingScore": 55, "tuitionRange": "450,000 - 800,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Шығыс Қазақстандағы ірі білім ордасы.", "contactPhone": "+7 (7232) 24-14-01", "email": "info@vku.edu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Қазақстан көшесі 55, Өскемен", "website": "vku.edu.kz", "averageRating": 4.2, "studentCount": 9000},
    {"id": "33", "name": "Семейдің Шәкәрім атындағы университеті", "city": "Семей", "logoUrl": "assets/images/shakarim_logo.png", "imageUrls": ["assets/images/shakarim_campus.jpg"], "majors": ["Педагогика", "Ветеринария", "Ауыл шаруашылығы", "IT", "Экономика"], "passingScore": 50, "tuitionRange": "400,000 - 700,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Семей өңіріндегі тарихи оқу орны.", "contactPhone": "+7 (7222) 56-56-10", "email": "info@shakarim.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Глинка көшесі 20А, Семей", "website": "shakarim.kz", "averageRating": 4.0, "studentCount": 10000},
    {"id": "34", "name": "Семей Медицина Университеті (СМУ)", "city": "Семей", "logoUrl": "assets/images/smu_logo.png", "imageUrls": ["assets/images/smu_campus.jpg"], "majors": ["Жалпы медицина", "Стоматология", "Қоғамдық денсаулық", "Педиатрия"], "passingScore": 75, "tuitionRange": "800,000 - 1,400,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Шығыс Қазақстандағы жалғыз медициналық жоғары оқу орны.", "contactPhone": "+7 (7222) 56-97-55", "email": "smu@smu.edu.kz", "requirements": ["ҰБТ 75+", "Медициналық анықтама"], "applicationDeadline": "20 тамыз, 2026", "address": "Абай көшесі 103, Семей", "website": "smu.edu.kz", "averageRating": 4.3, "studentCount": 5000},

    # URLSK & KYZYLORDA
    {"id": "35", "name": "М. Өтемісов атындағы Батыс Қазақстан университеті", "city": "Орал", "logoUrl": "assets/images/uralk_uni_logo.png", "imageUrls": ["assets/images/uralk_uni_campus.jpg"], "majors": ["Педагогика", "Өнер", "Тарих", "Филология", "IT"], "passingScore": 50, "tuitionRange": "450,000 - 750,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Орал қаласындағы көне университет.", "contactPhone": "+7 (7112) 51-40-51", "email": "wksu@wksu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Нұрсұлтан Назарбаев даңғылы 162, Орал", "website": "wksu.kz", "averageRating": 4.0, "studentCount": 8000},
    {"id": "36", "name": "Қорқыт Ата атындағы Қызылорда университеті", "city": "Қызылорда", "logoUrl": "assets/images/kyzylorda_uni_logo.png", "imageUrls": ["assets/images/kyzylorda_uni_campus.jpg"], "majors": ["Мұнай-газ ісі", "Құрылыс", "Педагогика", "Аграрлық іс", "IT"], "passingScore": 50, "tuitionRange": "450,000 - 750,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Сыр өңірінің жетекші университеті.", "contactPhone": "+7 (7242) 26-15-51", "email": "info@korkyt.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Төле би көшесі 36, Қызылорда", "website": "korkyt.kz", "averageRating": 4.1, "studentCount": 9000},
    
    # KOSTANAY & PETROPAVLOVSK
    {"id": "37", "name": "А. Байтұрсынов атындағы Қостанай өңірлік университеті", "city": "Қостанай", "logoUrl": "assets/images/kostanay_uni_logo.png", "imageUrls": ["assets/images/kostanay_campus.jpg"], "majors": ["Педагогика", "Аграрлық іс", "Инженерия", "IT", "Экономика"], "passingScore": 50, "tuitionRange": "450,000 - 750,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Солтүстік өңірдің ірі ЖОО.", "contactPhone": "+7 (7142) 51-11-98", "email": "info@ksu.edu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Байтұрсынов көшесі 47, Қостанай", "website": "ksu.edu.kz", "averageRating": 4.0, "studentCount": 8500},
    {"id": "38", "name": "М. Қозыбаев атындағы Солтүстік Қазақстан университеті", "city": "Петропавл", "logoUrl": "assets/images/sku_logo.png", "imageUrls": ["assets/images/sku_campus.jpg"], "majors": ["Педагогика", "Радиоэлектроника", "Ауыл шаруашылығы", "Экономика"], "passingScore": 50, "tuitionRange": "450,000 - 750,000 ₸/жыл", "hasDormitory": True, "hasGrants": True, "description": "Аризона университетімен косдипломдық бағдарлама бар.", "contactPhone": "+7 (7152) 49-32-33", "email": "mail@ku.edu.kz", "requirements": ["Аттестат", "ҰБТ"], "applicationDeadline": "25 тамыз, 2026", "address": "Пушкин көшесі 86, Петропавл", "website": "ku.edu.kz", "averageRating": 4.2, "studentCount": 7000},
]

# Generate Dart code
dart_code = f'''import '../models/university.dart';

// ------------------------------------------------------------------------
// AUTO-GENERATED DATABASE of {len(UNIVERSITIES)} UNIVERSITIES
// Inspired by joo.kz and local data sources to provide comprehensive coverage
// ------------------------------------------------------------------------

final List<University> sampleUniversities = [
'''

for u in UNIVERSITIES:
    majors_str = ", ".join([f"'{m}'" for m in u["majors"]])
    req_str = ", ".join([f"'{r}'" for r in u["requirements"]])
    img_str = ", ".join([f"'{img}'" for img in u.get("imageUrls", ["assets/images/default_campus.jpg"])])
    logo_url = u.get("logoUrl", "assets/images/default_logo.png")
    
    dart_code += f'''  University(
    id: '{u["id"]}',
    name: '{u["name"]}',
    city: '{u["city"]}',
    logoUrl: '{logo_url}',
    imageUrls: [{img_str}],
    majors: [{majors_str}],
    passingScore: {u["passingScore"]},
    tuitionRange: '{u["tuitionRange"]}',
    hasDormitory: {'true' if u["hasDormitory"] else 'false'},
    hasGrants: {'true' if u["hasGrants"] else 'false'},
    description: '{u["description"].replace("'", r"\'")}',
    requirements: [{req_str}],
    applicationDeadline: '{u["applicationDeadline"]}',
    address: '{u["address"]}',
    website: '{u["website"]}',
    contactPhone: '{u["contactPhone"]}',
    email: '{u["email"]}',
    averageRating: {u.get("averageRating", 4.0)},
    studentCount: {u.get("studentCount", 5000)},
  ),
'''

dart_code += "];\n"

# Write to universities.dart
output_path = r"C:\\Users\\User.DESKTOP-T27SALG\\Downloads\\project\\Project TANDAU app\\tandau\\lib\\data\\universities.dart"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(dart_code)

print(f"Successfully generated {len(UNIVERSITIES)} universities into {output_path}")
